### ISSUE TITLE
APLHA ROADMAP

### ISSUE THREAD

**Issue by Buuz135** [Beyond-Reality/Beyond-Reality-Capsule-Corporation#2]
- [ ] Force Dyonovan to make the progression mod
- [ ] Wait until release of new Capsule Mod
- [ ] Get a mod to set up the world type automatically
- [ ] Get a BQ theme
- [ ] Fix custom main menu resizing
- [ ] Create a logo for BQ
- [ ] Create "Lootbags" drops (report that the add button is offscreen)
